Cell 1 — Import libraries and select Excel file

In [1]:
import numpy as np
import pandas as pd
import tkinter as tk
from tkinter import filedialog

root = tk.Tk()
root.withdraw()

file_path = filedialog.askopenfilename(
    title="Select Weather Dataset",
    filetypes=[
        ("Excel files", "*.xlsx *.xls"),
        ("All files", "*.*")
    ]
)

root.destroy()

if not file_path:
    raise FileNotFoundError("No dataset was selected.")

df = pd.read_excel(file_path)

numeric_columns = [
    "temperature_c",
    "relative_humidity",
    "wind_speed",
    "precipitation_amount",
    "cloud_cover",
    "lifted_index"
]

for col in numeric_columns:
    df.fillna({col: df[col].median()}, inplace=True)

print("Dataset loaded successfully.")
print("File:", file_path)
print("Dataset shape:", df.shape)

print("\nColumns analyzed:")
print(numeric_columns)

print(
    "\nObservation: The weather dataset was successfully "
    "loaded and numerical weather attributes were selected "
    "for statistical analysis."
)

Dataset loaded successfully.
File: C:/Users/kjsce_mech37/Downloads/india_weather_103cities_30mar_13apr.xlsx
Dataset shape: (12360, 16)

Columns analyzed:
['temperature_c', 'relative_humidity', 'wind_speed', 'precipitation_amount', 'cloud_cover', 'lifted_index']

Observation: The weather dataset was successfully loaded and numerical weather attributes were selected for statistical analysis.

Cell 2 — Manual statistical functions

In [2]:
def manual_mean(data):
    data = list(data)
    total = 0

    for value in data:
        total += value

    return total / len(data)


def manual_median(data):
    data = sorted(list(data))
    n = len(data)

    if n % 2 == 1:
        return data[n // 2]

    return (data[n // 2 - 1] + data[n // 2]) / 2


def manual_mode(data):
    frequency = {}

    for value in data:
        if value in frequency:
            frequency[value] += 1
        else:
            frequency[value] = 1

    maximum_frequency = 0
    modes = []

    for value in frequency:
        if frequency[value] > maximum_frequency:
            maximum_frequency = frequency[value]
            modes = [value]

        elif frequency[value] == maximum_frequency:
            modes.append(value)

    return modes, maximum_frequency


def manual_variance(data):
    data = list(data)
    mean = manual_mean(data)
    total = 0

    for value in data:
        total += (value - mean) ** 2

    return total / (len(data) - 1)


def manual_standard_deviation(data):
    return manual_variance(data) ** 0.5


def manual_quartile(data, position):
    data = sorted(list(data))
    n = len(data)

    if position == 1:
        lower = data[:n // 2]
        return manual_median(lower)

    if position == 3:
        upper = data[(n + 1) // 2:]
        return manual_median(upper)


def manual_iqr(data):
    q1 = manual_quartile(data, 1)
    q3 = manual_quartile(data, 3)

    return q3 - q1


def manual_frequency(data):
    frequency = {}

    for value in data:
        if value in frequency:
            frequency[value] += 1
        else:
            frequency[value] = 1

    return frequency


print("Manual statistical functions created successfully.")

print(
    "Observation: Mean, mode, median, variance, standard deviation, "
    "quartiles, IQR and frequency calculations were implemented manually."
)

Manual statistical functions created successfully.
Observation: Mean, mode, median, variance, standard deviation, quartiles, IQR and frequency calculations were implemented manually.

Cell 3 — Statistical analysis of each numerical attribute

In [3]:
for column in numeric_columns:

    data = df[column].dropna().tolist()

    mean_value = manual_mean(data)
    median_value = manual_median(data)
    mode_values, mode_frequency = manual_mode(data)
    variance_value = manual_variance(data)
    standard_deviation = manual_standard_deviation(data)

    q1 = manual_quartile(data, 1)
    q3 = manual_quartile(data, 3)
    iqr_value = manual_iqr(data)

    print("\n" + "=" * 75)
    print("STATISTICS FOR:", column)
    print("=" * 75)

    print("Frequency:", len(data))
    print("Mean:", mean_value)
    print("Mode:", mode_values)
    print("Mode Frequency:", mode_frequency)
    print("Median:", median_value)
    print("Variance:", variance_value)
    print("Standard Deviation:", standard_deviation)
    print("Q1:", q1)
    print("Q3:", q3)
    print("Interquartile Range:", iqr_value)

    print(
        "\nObservation: The statistical measures for",
        column,
        "describe its central tendency and dispersion."
    )

===========================================================================
STATISTICS FOR: temperature_c
===========================================================================
Frequency: 12360
Mean: 27.88826860841424
Mode: [28]
Mode Frequency: 1003
Median: 28.0
Variance: 37.963969491724065
Standard Deviation: 6.161490849763884
Q1: 24.0
Q3: 32.0
Interquartile Range: 8.0

Observation: The statistical measures for temperature_c describe its central tendency and dispersion.

===========================================================================
STATISTICS FOR: relative_humidity
===========================================================================
Frequency: 12360
Mean: 25.038430420711975
Mode: [10]
Mode Frequency: 923
Median: 14.0
Variance: 590.2389146007043
Standard Deviation: 24.29483308443802
Q1: 6.0
Q3: 39.0
Interquartile Range: 33.0

Observation: The statistical measures for relative_humidity describe its central tendency and dispersion.

===========================================================================
STATISTICS FOR: wind_speed
===========================================================================
Frequency: 12360
Mean: 2.321925566343042
Mode: [2]
Mode Frequency: 8418
Median: 2.0
Variance: 0.2657219978574664
Standard Deviation: 0.5154822963569811
Q1: 2.0
Q3: 3.0
Interquartile Range: 1.0

Observation: The statistical measures for wind_speed describe its central tendency and dispersion.

===========================================================================
STATISTICS FOR: precipitation_amount
===========================================================================
Frequency: 12360
Mean: 0.11739482200647249
Mode: [0]
Mode Frequency: 10083
Median: 0.0
Variance: 0.8533586951427544
Standard Deviation: 0.9237741580834324
Q1: 0.0
Q3: 0.0
Interquartile Range: 0.0

Observation: The statistical measures for precipitation_amount describe its central tendency and dispersion.

===========================================================================
STATISTICS FOR: cloud_cover
===========================================================================
Frequency: 12360
Mean: 4.743122977346278
Mode: [1]
Mode Frequency: 3356
Median: 5.0
Variance: 9.608658908735697
Standard Deviation: 3.099783687410413
Q1: 1.0
Q3: 8.0
Interquartile Range: 7.0

Observation: The statistical measures for cloud_cover describe its central tendency and dispersion.

===========================================================================
STATISTICS FOR: lifted_index
===========================================================================
Frequency: 12360
Mean: 0.851294498381877
Mode: [2]
Mode Frequency: 6005
Median: 2.0
Variance: 7.484479269198485
Standard Deviation: 2.7357776351886653
Q1: -1.0
Q3: 2.0
Interquartile Range: 3.0

Observation: The statistical measures for lifted_index describe its central tendency and dispersion.

Cell 4 — Frequency analysis

In [4]:
print("\n" + "=" * 75)
print("WEATHER FREQUENCY")
print("=" * 75)

weather_frequency = manual_frequency(
    df["weather"].dropna().tolist()
)

for value in weather_frequency:
    print(value, ":", weather_frequency[value])

print(
    "\nObservation: The frequency distribution shows how often "
    "each weather condition occurs in the dataset."
)


print("\n" + "=" * 75)
print("PRECIPITATION TYPE FREQUENCY")
print("=" * 75)

precipitation_frequency = manual_frequency(
    df["precipitation_type"].dropna().tolist()
)

for value in precipitation_frequency:
    print(value, ":", precipitation_frequency[value])

print(
    "\nObservation: The precipitation frequency distribution "
    "shows the occurrence of different precipitation types."
)

===========================================================================
WEATHER FREQUENCY
===========================================================================
ishowerday : 181
cloudyday : 1612
oshowerday : 107
ishowernight : 216
tsnight : 523
rainnight : 37
pcloudyday : 438
oshowernight : 100
tsday : 569
tsrainday : 2
lightrainday : 446
humidday : 3
clearday : 4007
clearnight : 558
pcloudynight : 277
mcloudyday : 2003
cloudynight : 655
mcloudynight : 242
rainday : 10
lightrainnight : 336
tsrainnight : 1
humidnight : 32
lightsnowday : 3
lightsnownight : 2

Observation: The frequency distribution shows how often each weather condition occurs in the dataset.

===========================================================================
PRECIPITATION TYPE FREQUENCY
===========================================================================
rain : 1499
none : 10856
snow : 5

Observation: The precipitation frequency distribution shows the occurrence of different precipitation types.

Cell 5 — Grouped data analysis by city

In [5]:
cities = df["city"].dropna().unique()

for city in cities:

    city_data = df[df["city"] == city]

    print("\n" + "-" * 75)
    print("CITY:", city)
    print("-" * 75)

    for column in numeric_columns:

        data = city_data[column].dropna().tolist()

        if len(data) < 2:
            continue

        mean_value = manual_mean(data)
        median_value = manual_median(data)
        mode_values, mode_frequency = manual_mode(data)
        variance_value = manual_variance(data)
        standard_deviation = manual_standard_deviation(data)

        q1 = manual_quartile(data, 1)
        q3 = manual_quartile(data, 3)
        iqr_value = manual_iqr(data)

        print("\n", column)
        print("Frequency:", len(data))
        print("Mean:", mean_value)
        print("Mode:", mode_values)
        print("Mode Frequency:", mode_frequency)
        print("Median:", median_value)
        print("Variance:", variance_value)
        print("Standard Deviation:", standard_deviation)
        print("Q1:", q1)
        print("Q3:", q3)
        print("Interquartile Range:", iqr_value)

    print(
        "\nObservation: The numerical weather attributes were "
        "analyzed separately for",
        city,
        "to compare their statistical characteristics."
    )

---------------------------------------------------------------------------
CITY: Agartala
---------------------------------------------------------------------------

 temperature_c
Frequency: 120
Mean: 27.275
Mode: [25]
Mode Frequency: 18
Median: 26.0
Variance: 17.427941176470583
Standard Deviation: 4.174678571635257
Q1: 24.0
Q3: 30.0
Interquartile Range: 6.0

 relative_humidity
Frequency: 120
Mean: 41.75833333333333
Mode: [10]
Mode Frequency: 13
Median: 32.0
Variance: 1141.2772408963579
Standard Deviation: 33.78279504268937
Q1: 11.0
Q3: 77.5
Interquartile Range: 66.5

 wind_speed
Frequency: 120
Mean: 2.4166666666666665
Mode: [2]
Mode Frequency: 67
Median: 2.0
Variance: 0.3459383753501412
Standard Deviation: 0.5881652619376132
Q1: 2.0
Q3: 3.0
Interquartile Range: 1.0

 precipitation_amount
Frequency: 120
Mean: 0.18333333333333332
Mode: [0]
Mode Frequency: 89
Median: 0.0
Variance: 3.2602240896358468
Standard Deviation: 1.8056090633456199
Q1: 0.0
Q3: 0.0
Interquartile Range: 0.0

 cloud_cover
Frequency: 120
Mean: 5.008333333333334
Mode: [1, 4, 9]
Mode Frequency: 16
Median: 5.0
Variance: 7.1679971988795534
Standard Deviation: 2.6773115617872256
Q1: 3.0
Q3: 7.0
Interquartile Range: 4.0

 lifted_index
Frequency: 120
Mean: -1.525
Mode: [-1]
Mode Frequency: 43
Median: -1.0
Variance: 8.167436974789908
Standard Deviation: 2.8578728059152505
Q1: -4.0
Q3: 2.0
Interquartile Range: 6.0

Observation: The numerical weather attributes were analyzed separately for Agartala to compare their statistical characteristics.

---------------------------------------------------------------------------
CITY: Agra
---------------------------------------------------------------------------

 temperature_c
Frequency: 120
Mean: 27.566666666666666
Mode: [28]
Mode Frequency: 13
Median: 27.0
Variance: 28.214005602240896
Standard Deviation: 5.311685758988467
Q1: 24.0
Q3: 31.0
Interquartile Range: 7.0

 relative_humidity
Frequency: 120
Mean: 18.016666666666666
Mode: [4]
Mode Frequency: 12
Median: 14.0
Variance: 221.99971988795522
Standard Deviation: 14.899655025803625
Q1: 6.0
Q3: 28.0
Interquartile Range: 22.0

 wind_speed
Frequency: 120
Mean: 2.2583333333333333
Mode: [2]
Mode Frequency: 88
Median: 2.0
Variance: 0.22682072829131694
Standard Deviation: 0.4762569981546906
Q1: 2.0
Q3: 3.0
Interquartile Range: 1.0

 precipitation_amount
Frequency: 120
Mean: 0.11666666666666667
Mode: [0]
Mode Frequency: 93
Median: 0.0
Variance: 0.7929971988795549
Standard Deviation: 0.89050390166442
Q1: 0.0
Q3: 0.0
Interquartile Range: 0.0

 cloud_cover
Frequency: 120
Mean: 5.925
Mode: [9]
Mode Frequency: 48
Median: 7.0
Variance: 10.322058823529412
Standard Deviation: 3.212796106747114
Q1: 3.0
Q3: 9.0
Interquartile Range: 6.0

 lifted_index
Frequency: 120
Mean: 1.7083333333333333
Mode: [2]
Mode Frequency: 67
Median: 2.0
Variance: 5.838585434173683
Standard Deviation: 2.4163165012418557
Q1: -1.0
Q3: 2.0
Interquartile Range: 3.0

Observation: The numerical weather attributes were analyzed separately for Agra to compare their statistical characteristics.

---------------------------------------------------------------------------
CITY: Ahmedabad
---------------------------------------------------------------------------

 temperature_c
Frequency: 120
Mean: 30.6
Mode: [28]
Mode Frequency: 16
Median: 30.0
Variance: 21.821848739495803
Standard Deviation: 4.671386168954115
Q1: 27.5
Q3: 34.0
Interquartile Range: 6.5

 relative_humidity
Frequency: 120
Mean: 22.966666666666665
Mode: [0, -2]
Mode Frequency: 12
Median: 16.0
Variance: 552.6879551820726
Standard Deviation: 23.509316348674894
Q1: 2.0
Q3: 39.5
Interquartile Range: 37.5

 wind_speed
Frequency: 120
Mean: 2.325
Mode: [2]
Mode Frequency: 81
Median: 2.0
Variance: 0.22121848739495795
Standard Deviation: 0.4703386943415967
Q1: 2.0
Q3: 3.0
Interquartile Range: 1.0

 precipitation_amount
Frequency: 120
Mean: 0.075
Mode: [0]
Mode Frequency: 101
Median: 0.0
Variance: 1.3640756302521053
Standard Deviation: 1.1679364838261135
Q1: 0.0
Q3: 0.0
Interquartile Range: 0.0

 cloud_cover
Frequency: 120
Mean: 4.391666666666667
Mode: [1]
Mode Frequency: 43
Median: 4.0
Variance: 10.525980392156871
Standard Deviation: 3.2443767340056042
Q1: 1.0
Q3: 8.0
Interquartile Range: 7.0

 lifted_index
Frequency: 120
Mean: 0.21666666666666667
Mode: [2]
Mode Frequency: 71
Median: 2.0
Variance: 7.4988795518207185
Standard Deviation: 2.738408214971011
Q1: -1.0
Q3: 2.0
Interquartile Range: 3.0

Observation: The numerical weather attributes were analyzed separately for Ahmedabad to compare their statistical characteristics.

---------------------------------------------------------------------------
CITY: Aizawl
---------------------------------------------------------------------------

 temperature_c
Frequency: 120
Mean: 22.525
Mode: [17]
Mode Frequency: 19
Median: 20.0
Variance: 32.70525210084033
Standard Deviation: 5.718850592631384
Q1: 18.0
Q3: 26.5
Interquartile Range: 8.5

 relative_humidity
Frequency: 120
Mean: 36.9
Mode: [10]
Mode Frequency: 15
Median: 27.0
Variance: 1079.3680672268913
Standard Deviation: 32.85373749251204
Q1: 10.0
Q3: 70.5
Interquartile Range: 60.5

 wind_speed
Frequency: 120
Mean: 2.075
Mode: [2]
Mode Frequency: 111
Median: 2.0
Variance: 0.06995798319327734
Standard Deviation: 0.26449571488641804
Q1: 2.0
Q3: 2.0
Interquartile Range: 0.0

 precipitation_amount
Frequency: 120
Mean: 0.20833333333333334
Mode: [0]
Mode Frequency: 88
Median: 0.0
Variance: 1.5612745098039185
Standard Deviation: 1.249509707766978
Q1: 0.0
Q3: 0.0
Interquartile Range: 0.0

 cloud_cover
Frequency: 120
Mean: 3.9916666666666667
Mode: [1]
Mode Frequency: 33
Median: 3.0
Variance: 7.705812324929972
Standard Deviation: 2.7759344957923577
Q1: 1.0
Q3: 6.0
Interquartile Range: 5.0

 lifted_index
Frequency: 120
Mean: 2.225
Mode: [2]
Mode Frequency: 48
Median: 2.0
Variance: 9.4531512605042
Standard Deviation: 3.0745977396245188
Q1: -1.0
Q3: 6.0
Interquartile Range: 7.0

Observation: The numerical weather attributes were analyzed separately for Aizawl to compare their statistical characteristics.

---------------------------------------------------------------------------
CITY: Ajmer
---------------------------------------------------------------------------

 temperature_c
Frequency: 120
Mean: 26.266666666666666
Mode: [23]
Mode Frequency: 13
Median: 26.0
Variance: 19.188795518207282
Standard Deviation: 4.3805017427467465
Q1: 23.0
Q3: 29.0
Interquartile Range: 6.0

 relative_humidity
Frequency: 120
Mean: 20.758333333333333
Mode: [2]
Mode Frequency: 14
Median: 16.5
Variance: 400.5545518207289
Standard Deviation: 20.013858993725545
Q1: 2.0
Q3: 35.0
Interquartile Range: 33.0

 wind_speed
Frequency: 120
Mean: 2.283333333333333
Mode: [2]
Mode Frequency: 82
Median: 2.0
Variance: 0.23837535014005545
Standard Deviation: 0.4882369815366872
Q1: 2.0
Q3: 3.0
Interquartile Range: 1.0

 precipitation_amount
Frequency: 120
Mean: 0.11666666666666667
Mode: [0]
Mode Frequency: 95
Median: 0.0
Variance: 0.8770308123249332
Standard Deviation: 0.936499232420899
Q1: 0.0
Q3: 0.0
Interquartile Range: 0.0

 cloud_cover
Frequency: 120
Mean: 5.55
Mode: [9]
Mode Frequency: 40
Median: 6.0
Variance: 10.535294117647068
Standard Deviation: 3.2458117809951745
Q1: 1.5
Q3: 9.0
Interquartile Range: 7.5

 lifted_index
Frequency: 120
Mean: 1.0583333333333333
Mode: [2]
Mode Frequency: 73
Median: 2.0
Variance: 5.92093837535013
Standard Deviation: 2.43329783942495
Q1: -1.0
Q3: 2.0
Interquartile Range: 3.0

Observation: The numerical weather attributes were analyzed separately for Ajmer to compare their statistical characteristics.

---------------------------------------------------------------------------
CITY: Akola
---------------------------------------------------------------------------

 temperature_c
Frequency: 120
Mean: 31.541666666666668
Mode: [36]
Mode Frequency: 14
Median: 31.0
Variance: 22.838585434173677
Standard Deviation: 4.778973261504366
Q1: 28.0
Q3: 36.0
Interquartile Range: 8.0

 relative_humidity
Frequency: 120
Mean: 18.15
Mode: [0]
Mode Frequency: 14
Median: 14.5
Variance: 311.4899159663866
Standard Deviation: 17.649076915419304
Q1: 3.0
Q3: 30.5
Interquartile Range: 27.5

 wind_speed
Frequency: 120
Mean: 2.325
Mode: [2]
Mode Frequency: 85
Median: 2.0
Variance: 0.3556722689075644
Standard Deviation: 0.5963826530907521
Q1: 2.0
Q3: 3.0
Interquartile Range: 1.0

 precipitation_amount
Frequency: 120
Mean: 0.025
Mode: [0]
Mode Frequency: 103
Median: 0.0
Variance: 0.8985294117647055
Standard Deviation: 0.9479079131248486
Q1: 0.0
Q3: 0.0
Interquartile Range: 0.0

 cloud_cover
Frequency: 120
Mean: 3.15
Mode: [1]
Mode Frequency: 61
Median: 1.0
Variance: 8.094957983193256
Standard Deviation: 2.8451639642019324
Q1: 1.0
Q3: 4.5
Interquartile Range: 3.5

 lifted_index
Frequency: 120
Mean: 0.875
Mode: [2]
Mode Frequency: 75
Median: 2.0
Variance: 2.1271008403361344
Standard Deviation: 1.4584583779923699
Q1: -1.0
Q3: 2.0
Interquartile Range: 3.0

Observation: The numerical weather attributes were analyzed separately for Akola to compare their statistical characteristics.

---------------------------------------------------------------------------
CITY: Aligarh
---------------------------------------------------------------------------

 temperature_c
Frequency: 120
Mean: 26.941666666666666
Mode: [28]
Mode Frequency: 14
Median: 27.0
Variance: 33.09740896358544
Standard Deviation: 5.75303476120086
Q1: 23.0
Q3: 31.0
Interquartile Range: 8.0

 relative_humidity
Frequency: 120
Mean: 17.858333333333334
Mode: [0, 6]
Mode Frequency: 9
Median: 14.0
Variance: 220.13942577030812
Standard Deviation: 14.837096271518499
Q1: 6.0
Q3: 26.0
Interquartile Range: 20.0

 wind_speed
Frequency: 120
Mean: 2.341666666666667
Mode: [2]
Mode Frequency: 80
Median: 2.0
Variance: 0.24362745098039296
Standard Deviation: 0.4935863156332365
Q1: 2.0
Q3: 3.0
Interquartile Range: 1.0

 precipitation_amount
Frequency: 120
Mean: 0.11666666666666667
Mode: [0]
Mode Frequency: 95
Median: 0.0
Variance: 1.2803921568627488
Standard Deviation: 1.1315441471117018
Q1: 0.0
Q3: 0.0
Interquartile Range: 0.0

 cloud_cover
Frequency: 120
Mean: 5.966666666666667
Mode: [9]
Mode Frequency: 47
Median: 7.0
Variance: 10.41904761904762
Standard Deviation: 3.2278549563212438
Q1: 2.5
Q3: 9.0
Interquartile Range: 6.5

 lifted_index
Frequency: 120
Mean: 2.4166666666666665
Mode: [2]
Mode Frequency: 77
Median: 2.0
Variance: 4.833333333333322
Standard Deviation: 2.1984843263788174
Q1: 2.0
Q3: 2.0
Interquartile Range: 0.0

Observation: The numerical weather attributes were analyzed separately for Aligarh to compare their statistical characteristics.

---------------------------------------------------------------------------
CITY: Allahabad
---------------------------------------------------------------------------

 temperature_c
Frequency: 120
Mean: 30.566666666666666
Mode: [32]
Mode Frequency: 13
Median: 30.0
Variance: 31.188795518207293
Standard Deviation: 5.584692965437518
Q1: 26.0
Q3: 34.5
Interquartile Range: 8.5

 relative_humidity
Frequency: 120
Mean: 14.1
Mode: [0, 4, 6]
Mode Frequency: 12
Median: 10.0
Variance: 161.23361344537815
Standard Deviation: 12.697779862849181
Q1: 4.0
Q3: 21.0
Interquartile Range: 17.0

 wind_speed
Frequency: 120
Mean: 2.3666666666666667
Mode: [2]
Mode Frequency: 73
Median: 2.0
Variance: 0.2845938375350141
Standard Deviation: 0.5334733709708612
Q1: 2.0
Q3: 3.0
Interquartile Range: 1.0

 precipitation_amount
Frequency: 120
Mean: 0.058333333333333334
Mode: [0]
Mode Frequency: 108
Median: 0.0
Variance: 0.2738795518207291
Standard Deviation: 0.5233350282760835
Q1: 0.0
Q3: 0.0
Interquartile Range: 0.0

 cloud_cover
Frequency: 120
Mean: 4.458333333333333
Mode: [1]
Mode Frequency: 41
Median: 4.0
Variance: 10.58648459383752
Standard Deviation: 3.2536878451746905
Q1: 1.0
Q3: 8.0
Interquartile Range: 7.0

 lifted_index
Frequency: 120
Mean: 1.8666666666666667
Mode: [2]
Mode Frequency: 85
Median: 2.0
Variance: 4.250980392156864
Standard Deviation: 2.061790579122153
Q1: 2.0
Q3: 2.0
Interquartile Range: 0.0

Observation: The numerical weather attributes were analyzed separately for Allahabad to compare their statistical characteristics.

---------------------------------------------------------------------------
CITY: Ambattur
---------------------------------------------------------------------------

 temperature_c
Frequency: 120
Mean: 30.358333333333334
Mode: [28]
Mode Frequency: 17
Median: 29.0
Variance: 17.10581232492995
Standard Deviation: 4.135917349866889
Q1: 27.0
Q3: 34.0
Interquartile Range: 7.0

 relative_humidity
Frequency: 120
Mean: 34.53333333333333
Mode: [14]
Mode Frequency: 15
Median: 15.5
Variance: 920.6543417366945
Standard Deviation: 30.342286363039527
Q1: 11.0
Q3: 62.5
Interquartile Range: 51.5

 wind_speed
Frequency: 120
Mean: 2.45
Mode: [2]
Mode Frequency: 68
Median: 2.0
Variance: 0.2831932773109244
Standard Deviation: 0.532159071435341
Q1: 2.0
Q3: 3.0
Interquartile Range: 1.0

 precipitation_amount
Frequency: 120
Mean: 0.05
Mode: [0]
Mode Frequency: 115
Median: 0.0
Variance: 0.0647058823529413
Standard Deviation: 0.2543735095345844
Q1: 0.0
Q3: 0.0
Interquartile Range: 0.0

 cloud_cover
Frequency: 120
Mean: 4.875
Mode: [5]
Mode Frequency: 18
Median: 5.0
Variance: 6.631302521008403
Standard Deviation: 2.575131554116877
Q1: 2.5
Q3: 7.0
Interquartile Range: 4.5

 lifted_index
Frequency: 120
Mean: -0.7666666666666667
Mode: [-1]
Mode Frequency: 54
Median: -1.0
Variance: 5.676190476190489
Standard Deviation: 2.3824757031689723
Q1: -1.0
Q3: 2.0
Interquartile Range: 3.0

Observation: The numerical weather attributes were analyzed separately for Ambattur to compare their statistical characteristics.

---------------------------------------------------------------------------
CITY: Amravati
---------------------------------------------------------------------------

 temperature_c
Frequency: 120
Mean: 31.283333333333335
Mode: [33]
Mode Frequency: 14
Median: 32.0
Variance: 24.658543417366936
Standard Deviation: 4.965736946050096
Q1: 28.0
Q3: 35.0
Interquartile Range: 7.0

 relative_humidity
Frequency: 120
Mean: 16.916666666666668
Mode: [4]
Mode Frequency: 14
Median: 13.0
Variance: 274.0434173669465
Standard Deviation: 16.554256774828236
Q1: 4.0
Q3: 28.5
Interquartile Range: 24.5

 wind_speed
Frequency: 120
Mean: 2.183333333333333
Mode: [2]
Mode Frequency: 99
Median: 2.0
Variance: 0.16778711484593792
Standard Deviation: 0.40961825502037613
Q1: 2.0
Q3: 2.0
Interquartile Range: 0.0

 precipitation_amount
Frequency: 120
Mean: 0.025
Mode: [0]
Mode Frequency: 104
Median: 0.0
Variance: 0.7808823529411761
Standard Deviation: 0.8836754794273609
Q1: 0.0
Q3: 0.0
Interquartile Range: 0.0

 cloud_cover
Frequency: 120
Mean: 3.375
Mode: [1]
Mode Frequency: 54
Median: 2.0
Variance: 8.370798319327731
Standard Deviation: 2.893233194771505
Q1: 1.0
Q3: 5.5
Interquartile Range: 4.5

 lifted_index
Frequency: 120
Mean: 0.875
Mode: [2]
Mode Frequency: 75
Median: 2.0
Variance: 2.1271008403361344
Standard Deviation: 1.4584583779923699
Q1: -1.0
Q3: 2.0
Interquartile Range: 3.0

Observation: The numerical weather attributes were analyzed separately for Amravati to compare their statistical characteristics.

---------------------------------------------------------------------------
CITY: Amritsar
---------------------------------------------------------------------------

 temperature_c
Frequency: 120
Mean: 23.475
Mode: [22]
Mode Frequency: 10
Median: 22.5
Variance: 33.444747899159665
Standard Deviation: 5.783143427164821
Q1: 19.0
Q3: 28.0
Interquartile Range: 9.0

 relative_humidity
Frequency: 120
Mean: 23.2
Mode: [8]
Mode Frequency: 14
Median: 14.0
Variance: 472.54789915966364
Standard Deviation: 21.738166876709354
Q1: 8.0
Q3: 34.5
Interquartile Range: 26.5

 wind_speed
Frequency: 120
Mean: 2.216666666666667
Mode: [2]
Mode Frequency: 95
Median: 2.0
Variance: 0.1879551820728298
Standard Deviation: 0.4335379822724069
Q1: 2.0
Q3: 2.0
Interquartile Range: 0.0

 precipitation_amount
Frequency: 120
Mean: 0.21666666666666667
Mode: [0]
Mode Frequency: 88
Median: 0.0
Variance: 0.8434173669467802
Standard Deviation: 0.9183775731945877
Q1: 0.0
Q3: 0.0
Interquartile Range: 0.0

 cloud_cover
Frequency: 120
Mean: 6.108333333333333
Mode: [9]
Mode Frequency: 49
Median: 7.0
Variance: 9.61001400560224
Standard Deviation: 3.10000225896728
Q1: 3.0
Q3: 9.0
Interquartile Range: 6.0

 lifted_index
Frequency: 120
Mean: 2.466666666666667
Mode: [2]
Mode Frequency: 65
Median: 2.0
Variance: 6.049299719887947
Standard Deviation: 2.4595324189544536
Q1: 2.0
Q3: 6.0
Interquartile Range: 4.0

Observation: The numerical weather attributes were analyzed separately for Amritsar to compare their statistical characteristics.

---------------------------------------------------------------------------
CITY: Asansol
---------------------------------------------------------------------------

 temperature_c
Frequency: 120
Mean: 30.658333333333335
Mode: [30]
Mode Frequency: 14
Median: 30.0
Variance: 28.848669467787104
Standard Deviation: 5.371095741819085
Q1: 26.5
Q3: 34.5
Interquartile Range: 8.0

 relative_humidity
Frequency: 120
Mean: 19.133333333333333
Mode: [6]
Mode Frequency: 11
Median: 12.5
Variance: 342.9400560224095
Standard Deviation: 18.51864077146078
Q1: 6.0
Q3: 25.0
Interquartile Range: 19.0

 wind_speed
Frequency: 120
Mean: 2.3
Mode: [2]
Mode Frequency: 82
Median: 2.0
Variance: 0.22857142857142868
Standard Deviation: 0.47809144373375756
Q1: 2.0
Q3: 3.0
Interquartile Range: 1.0

 precipitation_amount
Frequency: 120
Mean: 0.16666666666666666
Mode: [0]
Mode Frequency: 95
Median: 0.0
Variance: 0.44257703081232525
Standard Deviation: 0.6652646321670236
Q1: 0.0
Q3: 0.0
Interquartile Range: 0.0

 cloud_cover
Frequency: 120
Mean: 4.308333333333334
Mode: [1]
Mode Frequency: 36
Median: 4.0
Variance: 9.357913165266107
Standard Deviation: 3.0590706375084094
Q1: 1.0
Q3: 7.0
Interquartile Range: 6.0

 lifted_index
Frequency: 120
Mean: 1.1583333333333334
Mode: [2]
Mode Frequency: 78
Median: 2.0
Variance: 4.689005602240903
Standard Deviation: 2.165411185489006
Q1: -1.0
Q3: 2.0
Interquartile Range: 3.0

Observation: The numerical weather attributes were analyzed separately for Asansol to compare their statistical characteristics.

---------------------------------------------------------------------------
CITY: Aurangabad
---------------------------------------------------------------------------

 temperature_c
Frequency: 120
Mean: 29.458333333333332
Mode: [27]
Mode Frequency: 14
Median: 29.0
Variance: 21.34278711484594
Standard Deviation: 4.619825442031976
Q1: 26.0
Q3: 33.0
Interquartile Range: 7.0

 relative_humidity
Frequency: 120
Mean: 18.816666666666666
Mode: [2]
Mode Frequency: 15
Median: 16.5
Variance: 335.8484593837533
Standard Deviation: 18.32616870444429
Q1: 2.0
Q3: 30.5
Interquartile Range: 28.5

 wind_speed
Frequency: 120
Mean: 2.3583333333333334
Mode: [2]
Mode Frequency: 76
Median: 2.0
Variance: 0.2654761904761911
Standard Deviation: 0.5152438165336787
Q1: 2.0
Q3: 3.0
Interquartile Range: 1.0

 precipitation_amount
Frequency: 120
Mean: 0.025
Mode: [0]
Mode Frequency: 102
Median: 0.0
Variance: 0.7976890756302517
Standard Deviation: 0.8931344107301273
Q1: 0.0
Q3: 0.0
Interquartile Range: 0.0

 cloud_cover
Frequency: 120
Mean: 3.283333333333333
Mode: [1]
Mode Frequency: 60
Median: 1.5
Variance: 8.154341736694699
Standard Deviation: 2.855580805492063
Q1: 1.0
Q3: 5.0
Interquartile Range: 4.0

 lifted_index
Frequency: 120
Mean: 0.9333333333333333
Mode: [2]
Mode Frequency: 77
Median: 2.0
Variance: 2.617366946778715
Standard Deviation: 1.617827848313508
Q1: -1.0
Q3: 2.0
Interquartile Range: 3.0

Observation: The numerical weather attributes were analyzed separately for Aurangabad to compare their statistical characteristics.

---------------------------------------------------------------------------
CITY: Bangalore
---------------------------------------------------------------------------

 temperature_c
Frequency: 120
Mean: 28.491666666666667
Mode: [32]
Mode Frequency: 13
Median: 28.0

Cell 6 — Grouped frequency analysis

In [6]:
print("\n" + "=" * 75)
print("GROUPED WEATHER FREQUENCY BY CITY")
print("=" * 75)

grouped_weather = df.groupby(
    ["city", "weather"]
).size()

print(grouped_weather)

print(
    "\nObservation: Weather conditions were grouped by city "
    "and their frequencies were calculated to determine the "
    "distribution of weather conditions across different cities."
)

===========================================================================
GROUPED WEATHER FREQUENCY BY CITY
===========================================================================
city      weather
Agartala  clearday        18
          clearnight       3
          cloudyday       23
          cloudynight      2
          humidday         3
                          ..
Warangal  oshowernight     2
          pcloudyday      13
          pcloudynight     2
          tsday            4
          tsnight          4
Length: 1404, dtype: int64

Observation: Weather conditions were grouped by city and their frequencies were calculated to determine the distribution of weather conditions across different cities.

Cell 7 — Grouped temperature analysis

In [7]:
print("\n" + "=" * 75)
print("GROUPED TEMPERATURE ANALYSIS")
print("=" * 75)

grouped_temperature = {}

for city in cities:

    data = df[
        df["city"] == city
    ]["temperature_c"].dropna().tolist()

    if len(data) > 1:

        grouped_temperature[city] = {
            "Frequency": len(data),
            "Mean": manual_mean(data),
            "Mode": manual_mode(data)[0],
            "Median": manual_median(data),
            "Variance": manual_variance(data),
            "Standard Deviation": manual_standard_deviation(data),
            "Q1": manual_quartile(data, 1),
            "Q3": manual_quartile(data, 3),
            "IQR": manual_iqr(data)
        }

grouped_temperature_df = pd.DataFrame.from_dict(
    grouped_temperature,
    orient="index"
)

display(grouped_temperature_df)

print(
    "\nObservation: Temperature statistics were calculated "
    "separately for each city using the manual statistical procedures."
)

===========================================================================
GROUPED TEMPERATURE ANALYSIS
===========================================================================

,Frequency,Mean,Mode,Median,Variance,Standard Deviation,Q1,Q3,IQR
Agartala,120,27.275000,[25],26.0,17.427941,4.174679,24.0,30.0,6.0
Agra,120,27.566667,[28],27.0,28.214006,5.311686,24.0,31.0,7.0
Ahmedabad,120,30.600000,[28],30.0,21.821849,4.671386,27.5,34.0,6.5
Aizawl,120,22.525000,[17],20.0,32.705252,5.718851,18.0,26.5,8.5
Ajmer,120,26.266667,[23],26.0,19.188796,4.380502,23.0,29.0,6.0
...,...,...,...,...,...,...,...,...,...
Vadodara,120,30.433333,"[26, 29, 32, 27, 25]",30.0,25.961905,5.095283,26.0,34.0,8.0
Varanasi,120,30.233333,"[29, 32, 27]",30.0,35.743417,5.978580,26.0,34.5,8.5
Vijayawada,120,30.991667,[28],30.0,24.294048,4.928899,28.0,36.0,8.0
Visakhapatnam,120,29.533333,[28],29.0,16.234174,4.029165,27.0,32.0,5.0
Warangal,120,32.250000,[36],32.0,20.273109,4.502567,29.0,36.0,7.0

Observation: Temperature statistics were calculated separately for each city using the manual statistical procedures.

Cell 8 — Highest and lowest mean temperature

In [8]:
highest_mean_city = None
lowest_mean_city = None

highest_mean = None
lowest_mean = None

for city in grouped_temperature:

    mean_value = grouped_temperature[city]["Mean"]

    if highest_mean is None or mean_value > highest_mean:
        highest_mean = mean_value
        highest_mean_city = city

    if lowest_mean is None or mean_value < lowest_mean:
        lowest_mean = mean_value
        lowest_mean_city = city


print("\n" + "=" * 75)
print("TEMPERATURE COMPARISON")
print("=" * 75)

print(
    "\nCity with highest mean temperature:",
    highest_mean_city
)

print(
    "Mean temperature:",
    highest_mean
)

print(
    "\nCity with lowest mean temperature:",
    lowest_mean_city
)

print(
    "Mean temperature:",
    lowest_mean
)

print(
    "\nObservation: The cities with the highest and lowest "
    "average temperatures were identified by comparing their "
    "manually calculated mean values."
)

===========================================================================
TEMPERATURE COMPARISON
===========================================================================

City with highest mean temperature: Gulbarga
Mean temperature: 32.925

City with lowest mean temperature: Srinagar
Mean temperature: 8.475

Observation: The cities with the highest and lowest average temperatures were identified by comparing their manually calculated mean values.

Cell 9 — Outlier analysis

In [9]:
print("\n" + "=" * 75)
print("OUTLIER ANALYSIS FOR EACH NUMERICAL ATTRIBUTE")
print("=" * 75)

for column in numeric_columns:

    data = df[column].dropna().tolist()

    q1 = manual_quartile(data, 1)
    q3 = manual_quartile(data, 3)

    iqr_value = q3 - q1

    lower_bound = q1 - (1.5 * iqr_value)
    upper_bound = q3 + (1.5 * iqr_value)

    outliers = []

    for value in data:

        if value < lower_bound or value > upper_bound:
            outliers.append(value)

    print("\n" + "-" * 75)
    print("ATTRIBUTE:", column)
    print("-" * 75)

    print("Q1:", q1)
    print("Q3:", q3)
    print("IQR:", iqr_value)

    print("Lower Bound:", lower_bound)
    print("Upper Bound:", upper_bound)

    print("Number of Outliers:", len(outliers))

    print("\nOutlier Values:")

    if len(outliers) > 0:
        print(outliers)
    else:
        print("No outliers detected.")

    print(
        "\nObservation: Values below the lower bound or above "
        "the upper bound were classified as outliers using "
        "the 1.5 × IQR rule."
    )

===========================================================================
OUTLIER ANALYSIS FOR EACH NUMERICAL ATTRIBUTE
===========================================================================

---------------------------------------------------------------------------
ATTRIBUTE: temperature_c
---------------------------------------------------------------------------
Q1: 24.0
Q3: 32.0
IQR: 8.0
Lower Bound: 12.0
Upper Bound: 44.0
Number of Outliers: 166

Outlier Values:
[11, 11, 11, 10, 11, 11, 11, 11, 11, 11, 10, 10, 10, 11, 11, 10, 10, 11, 11, 11, 11, 11, 11, 11, 10, 10, 11, 11, 10, 10, 10, 11, 11, 11, 11, 10, 10, 10, 11, 10, 10, 9, 11, 10, 9, 8, 7, 8, 11, 10, 9, 7, 6, 6, 5, 11, 11, 8, 6, 6, 6, 10, 9, 9, 10, 11, 9, 8, 8, 11, 9, 9, 6, 6, 9, 10, 7, 5, 4, 3, 3, 3, 8, 8, 9, 6, 5, 4, 4, 7, 10, 9, 5, 6, 5, 5, 6, 10, 9, 10, 7, 6, 6, 5, 8, 10, 9, 5, 5, 4, 4, 3, 4, 8, 6, 3, 3, 3, 3, -1, 4, 7, 9, 6, 5, -1, 4, -1, 6, 9, 11, 11, 11, 8, 7, 7, 11, 9, 8, 8, 10, 11, 10, 9, 8, 7, 6, 5, 9, 11, 9, 6, 5, 4, 11, 9, 9, 8, 11, 10, 8, 5, 5, 9, 7, 6]

Observation: Values below the lower bound or above the upper bound were classified as outliers using the 1.5 × IQR rule.

---------------------------------------------------------------------------
ATTRIBUTE: relative_humidity
---------------------------------------------------------------------------
Q1: 6.0
Q3: 39.0
IQR: 33.0
Lower Bound: -43.5
Upper Bound: 88.5
Number of Outliers: 190

Outlier Values:
[98, 95, 99, 90, 95, 98, 98, 90, 99, 96, 93, 93, 89, 97, 90, 99, 99, 95, 95, 97, 97, 98, 95, 97, 99, 99, 95, 94, 93, 90, 90, 90, 94, 94, 92, 90, 90, 98, 89, 92, 91, 94, 90, 90, 89, 95, 93, 90, 92, 94, 95, 91, 92, 92, 90, 94, 90, 94, 91, 90, 90, 97, 92, 96, 97, 89, 89, 93, 96, 92, 95, 98, 93, 90, 89, 93, 91, 93, 89, 93, 90, 90, 89, 89, 90, 94, 93, 90, 93, 94, 94, 90, 96, 97, 92, 95, 91, 93, 95, 93, 90, 90, 90, 95, 92, 90, 91, 92, 90, 95, 91, 91, 95, 99, 91, 95, 99, 90, 90, 92, 95, 90, 91, 89, 93, 90, 94, 90, 99, 96, 95, 90, 90, 94, 89, 93, 90, 89, 90, 90, 90, 89, 92, 95, 94, 89, 95, 95, 89, 90, 93, 95, 90, 90, 93, 90, 91, 99, 90, 91, 92, 92, 90, 95, 94, 98, 91, 92, 90, 92, 97, 91, 91, 95, 97, 94, 95, 99, 97, 95, 92, 93, 95, 95, 90, 97, 89, 89, 95, 91]

Observation: Values below the lower bound or above the upper bound were classified as outliers using the 1.5 × IQR rule.

---------------------------------------------------------------------------
ATTRIBUTE: wind_speed
---------------------------------------------------------------------------
Q1: 2.0
Q3: 3.0
IQR: 1.0
Lower Bound: 0.5
Upper Bound: 4.5
Number of Outliers: 13

Outlier Values:
[5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]

Observation: Values below the lower bound or above the upper bound were classified as outliers using the 1.5 × IQR rule.

---------------------------------------------------------------------------
ATTRIBUTE: precipitation_amount
---------------------------------------------------------------------------
Q1: 0.0
Q3: 0.0
IQR: 0.0
Lower Bound: 0.0
Upper Bound: 0.0
Number of Outliers: 2277

Outlier Values:
[1, -4, 4, -4, 4, -4, 5, -5, 5, -5, 5, -5, 5, -5, 5, -5, 5, 1, 3, 1, 1, 1, 3, 1, 2, 2, 1, 1, 1, 1, 1, 1, -2, 2, -2, 2, -2, 2, -2, 2, -2, 2, -2, 2, -2, 3, -3, 3, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, -1, 1, -1, 1, -1, 1, -1, 1, 2, 1, -4, 5, -5, 5, -5, 5, 2, 2, -3, 3, -3, 3, -3, 3, -3, 3, -3, 3, -3, 3, -3, 3, -3, 3, 1, 3, 2, 2, 1, 1, 1, 1, 1, 2, 1, 3, 2, 2, 1, 1, 1, -1, 1, 1, -2, 2, -2, 2, -2, 2, -2, 2, -2, 3, -3, 3, -3, 3, 1, 1, 1, 1, 2, 3, 2, 1, -1, 2, -2, 2, -2, 2, -2, 3, -3, 3, -3, 3, -3, 3, -3, 3, -1, 1, 2, -3, 3, -3, 3, -3, 3, -3, 3, -3, 3, -3, 3, -3, 3, 1, 1, 1, 1, 3, 2, 2, 1, 2, -2, 2, -2, 2, -2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, -2, 2, -2, 2, -2, 2, -2, 3, -3, 3, -3, 3, -3, 3, 1, -1, 1, -1, 1, -1, 1, -1, 1, 1, 1, -3, 3, -3, 3, -3, 3, 1, 2, 2, 2, 3, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 3, 1, 1, 1, 2, 2, 2, 3, 2, 2, 1, 1, -1, 1, 1, -2, 2, -2, 2, -2, 2, -2, 3, -3, 3, -3, 3, -3, 3, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, 1, 1, 1, 1, -1, 1, -1, 1, -1, 1, -1, 1, 1, -2, 2, -2, 2, -2, 2, 1, 1, 1, 1, 1, 2, 1, 3, 1, 2, 1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, 1, 1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, 2, -3, 3, -3, 3, -3, 3, 2, 3, 1, 1, -1, 1, 1, -2, 2, -2, 2, -2, 2, -2, 3, -3, 3, -3, 3, -3, 3, 1, 1, 1, 1, -1, 2, -2, 2, -2, 2, -2, 2, 1, -3, 3, 1, -2, 3, -3, 3, -3, 3, -3, 3, -3, 3, -3, 3, -3, 4, -4, 4, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, 1, 3, 2, 4, 2, 3, 3, 1, 4, 3, 2, 1, 2, 2, 1, 1, 1, 1, -2, 2, -2, 2, -2, 2, -2, 2, -2, 2, -2, 3, -3, 3, -3, 3, 3, 3, 1, 2, 1, 1, 1, -2, 2, -2, 2, -2, 2, 1, 1, 3, 3, 3, 2, 2, 3, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, -1, 1, 1, -2, 2, -2, 2, -2, 2, -2, 2, -2, 2, -2, 2, -2, 3, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, 1, 3, 2, 4, 3, 1, 3, 1, 1, 3, 3, 3, 3, 1, 1, 2, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, 1, -2, 2, -2, 2, -2, 2, 1, 1, 2, 1, 2, 2, 2, 3, 2, 2, 1, -1, 2, 1, -3, 3, -3, 3, -3, 3, -3, 3, -3, 3, -3, 3, -3, 3, 1, 3, 2, 2, 1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, 1, -2, 2, 1, 2, 3, 3, 1, 1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 3, 2, 1, 3, 2, 2, 4, 3, 2, 1, 1, 1, -3, 3, -3, 3, -3, 3, -3, 3, -3, 3, -3, 3, -3, 3, -3, 3, 1, 2, 3, 2, 2, 3, 1, -1, 2, -2, 2, -2, 2, -2, 2, -2, 2, 1, -3, 3, -3, 3, -3, 3, 1, 3, 2, 1, 1, 2, 1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 2, -2, 3, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, -2, 2, 1, -3, 4, -4, 4, -4, 4, -4, 4, -4, 5, -5, 5, -5, 5, 2, 1, 2, 1, 1, 2, 1, 1, 1, 1, 2, 2, 2, 1, 1, 2, 2, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, -2, 2, 1, 1, 1, -1, 2, -2, 2, -2, 2, -2, 2, -2, 2, 1, -3, 3, -3, 3, -3, 3, 1, 1, 1, 1, 3, 1, 2, 2, 2, 2, 2, 1, -1, 1, 1, 1, 2, 1, 1, -1, 2, -2, 2, -2, 3, -3, 3, -3, 3, -3, 3, -3, 3, -3, 3, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, -3, 3, 1, -4, 4, -4, 4, -4, 4, -4, 4, -4, 4, -4, 4, -4, 4, 2, 1, 3, 2, 1, 3, 2, 1, 3, 2, 1, 2, 3, 3, 2, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, -2, 2, -2, 2, -2, 2, -2, 2, -2, 2, -2, 2, -2, 2, -2, 2, 1, 2, 2, 1, 2, 2, 2, 3, 1, 1, 1, -1, 1, 1, -2, 2, -2, 2, -2, 2, -2, 2, -2, 2, -2, 2, -2, 2, 2, 4, 2, 1, 1, 3, 1, 2, 3, 3, 2, 2, 3, 1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, 1, 1, -1, 1, -1, 1, -1, 1, -1, 1, 1, -2, 2, -2, 2, -2, 2, 1, 1, 1, -2, 2, 1, -3, 4, -4, 4, -4, 4, -4, 4, -4, 4, -4, 4, -4, 4, 1, 3, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, -1, 2, -2, 2, -2, 2, 1, -3, 3, -3, 3, -3, 3, -3, 3, -3, 3, 1, 1, 1, -2, 2, 1, -3, 3, -3, 4, -4, 4, -4, 4, 1, -5, 5, -5, 5, -5, 6, 2, 2, 2, 1, 1, 2, 3, 2, 2, 1, 1, 1, 2, 3, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 3, 2, 2, 1, -1, 1, -1, 1, -1, 1, -1, 1, 1, -2, 2, 1, -3, 3, -3, 3, -3, 3, 1, 1, 1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, 1, 1, -3, 3, -3, 3, -3, 3, 1, 1, 1, 3, 2, 2, 1, 2, 2, 1, 1, 1, 1, -3, 3, -3, 3, -3, 3, 1, 2, 3, 4, 3, 2, 1, 1, 2, 1, 1, 1, 1, -2, 3, -3, 3, -3, 3, -3, 3, -3, 3, 1, -4, 4, -4, 4, -4, 4, 1, 3, 3, 3, 3, 3, 3, 1, 1, 2, 2, 2, 3, 2, 1, 2, -3, 3, -3, 3, -3, 3, 1, 3, 2, 1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 2, -2, 3, 4, 2, 3, 1, 3, 3, 1, 1, 3, 1, -1, 2, -2, 2, -2, 3, -3, 3, -3, 3, -3, 3, -3, 3, -3, 3, 2, 1, 1, 2, 1, 3, 3, 1, 1, 1, 1, -3, 3, -3, 3, -3, 3, -3, 3, -3, 3, -3, 3, -3, 3, -3, 3, 1, 2, 1, 1, 1, 1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 2, -2, 2, 1, 1, 3, 1, 2, 3, 3, 1, 1, -3, 4, -4, 4, -4, 4, -4, 4, -4, 4, -4, 4, -4, 4, -4, 4, 1, 1, 2, 2, 1, 1, 3, 3, 3, 1, 1, 2, 1, 1, 2, 3, 1, 1, 1, 2, 1, 1, -2, 2, -2, 2, -2, 2, -2, 2, -2, 2, -2, 2, -2, 2, -1, 1, 1, -2, 2, -2, 2, -2, 2, -2, 2, -2, 2, -2, 2, -2, 2, 3, 2, 1, 2, 3, 1, 1, 2, 3, 3, 2, 1, 3, 1, 2, -3, 3, -3, 3, -3, 3, -3, 3, -3, 3, -3, 3, -3, 3, -3, 3, 1, 1, 1, 1, 1, 2, 2, 2, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, 1, 1, 2, 1, 2, 2, 2, 1, 1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, 1, 1, 2, 1, 1, 2, 3, 1, 1, 2, 1, 1, -1, 1, -1, 1, -1, 1, -1, 1, 1, -2, 2, -2, 2, -2, 2, 1, 1, 1, 2, 3, 3, 1, 1, 1, 1, 3, 2, 1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 3, -3, 3, -3, 3, 3, 1, 1, 2, 2, 2, 1, 1, -2, 3, -3, 3, -3, 3, -3, 3, -3, 3, -3, 3, -3, 3, -3, 3, -1, 1, 1, 1, -3, 3, -3, 3, -3, 3, -3, 3, -3, 3, -3, 3, -3, 3, 1, 2, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, 1, 1, 2, 2, 3, 2, 3, 3, 3, 1, 1, 1, -1, 1, -1, 1, -1, 2, 1, 1, 1, 1, 2, 1, 2, 3, 3, 2, 2, 1, -1, 2, -2, 2, -2, 2, -2, 2, -2, 2, 1, 1, 1, 1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, 1, 2, 1, 1, 1, -1, 1, -1, 1, -1, 1, 1, -2, 2, -2, 3, -3, 3, -3, 3, -3, 3, 1, 1, -2, 2, -2, 2, 1, -3, 3, -3, 3, -3, 3, -3, 3, -3, 3, 1, 1, -3, 3, -3, 3, -3, 3, -3, 3, -3, 3, -3, 3, -3, 3, -3, 3, 1, 1, -1, 2, -2, 2, -2, 2, -2, 2, -2, 2, 1, 1, 2, 1, -1, 2, -2, 2, -2, 2, -2, 2, -2, 2, 1, -3, 3, -3, 3, -3, 3, 1, 3, 1, 2, 2, 1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, 1, -1, 1, 1, 1, 1, 1, 2, 1, 1, -2, 2, -2, 2, -2, 2, 1, -3, 3, -3, 3, -3, 3, -3, 3, -3, 3, 1, -1, 1, 1, -2, 2, -2, 2, -2, 2, -2, 2, 1, -3, 3, -3, 3, -3, 3, 2, 1, 1, 1, 2, 1, -4, 4, -4, 4, -4, 4, 1, 1, 1, 1, 1, -1, 1, -1, 1, 1, -2, 2, 3, 1, 1, 2, 2, 1, 1, 1, 3, 1, 1, 1, -1, 1, -1, 1, -1, 1, -1, 1, 1, -2, 2, -2, 2, 1, -3, 3, 1, 3, 3, 1, 1, 1, 1, 2, 1, 1, 1, 3, 4, 3, 1, 1, -1, 1, -1, 1, -1, 1, 1, 1, 1, 1, 3, 3, 3, 2, 2, 3, 1, 1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 2, -2, 2, -2, 2, 1, 1, 1, 1, 2, 4, 1, 1, 3, 2, 1, 1, -1, 1, -1, 1, -1, 1, -1, 2, -2, 2, -2, 2, -2, 2, 2, -3, 3, 1, -4, 4, -4, 4, -4, 4, -4, 4, 1, -5, 5, -5, 5, -5, 5, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, 1, 1, -3, 3, -3, 3, -3, 3, 1, 1, 1, 2, 2, 3, 1, 3, 3, 3, 2, 1, 1, 2, 2, 1, 1, -1, 1, 1, 1, -3, 3, -3, 3, -3, 3, -3, 3, -3, 3, -3, 3, -3, 3, 1, 1, 1, 3, 2, 2, 1, 1, 3, 1, 1, 1, 1, -1, 1, 1, -2, 2, -2, 2, -2, 2, -2, 2, -2, 2, -2, 2, -2, 2, 1, 1, -3, 4, 1, -5, 5, -5, 5, -5, 5, -5, 5, 1, -6, 6, -6, 6, -6, 6, 1, 1, 1, 1, 1, 2, 3, 3, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, 2, -2, 2, -2, 2, -2, 2, -2, 2, 1, -1, 2, -2, 2, -2, 2, 1, 2, 1, 3, 1, 1, 1, -1, 1, -1, 1, 1, -2, 2, -2, 2, -2, 2, 3, 1, 1, 1, 2, 1, 1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 2, -2, 2, -2, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, -1, 2, -2, 2, -2, 2, -2, 2, -2, 2, 1, 1, -4, 4, -4, 4, -4, 4, 1, 1, 1, 1, -2, 3, -3, 3, -3, 3, -3, 3, -3, 3, -3, 3, -3, 4, -4, 4, 2, 1, 1, -1, 2, -2, 2, -2, 2, -2, 2, -2, 2, 1, -1, 1, -1, 1, -1, 1, -1, 1, 1, 1, -3, 4, -4, 4, -4, 4, 1, 1, 1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 2, -2, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, 1, 1, 1, 1, 1, 1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 1, -1, 2, -2, 2, 1, 3]

Observation: Values below the lower bound or above the upper bound were classified as outliers using the 1.5 × IQR rule.

---------------------------------------------------------------------------
ATTRIBUTE: cloud_cover
---------------------------------------------------------------------------
Q1: 1.0
Q3: 8.0
IQR: 7.0
Lower Bound: -9.5
Upper Bound: 18.5
Number of Outliers: 0

Outlier Values:
No outliers detected.

Observation: Values below the lower bound or above the upper bound were classified as outliers using the 1.5 × IQR rule.

---------------------------------------------------------------------------
ATTRIBUTE: lifted_index
---------------------------------------------------------------------------
Q1: -1.0
Q3: 2.0
IQR: 3.0
Lower Bound: -5.5
Upper Bound: 6.5
Number of Outliers: 301

Outlier Values:
[-6, -6, -10, -6, -6, -6, -6, -10, -10, 10, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, 10, -6, -6, -6, 15, 15, 15, 10, -6, -6, -6, -6, 10, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -10, -10, -10, -10, -10, -6, -6, -6, -6, -10, -10, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, 10, 10, -6, -6, -6, -6, -10, -10, -10, -10, -10, -10, -6, -6, 10, -6, -6, -6, -6, -6, -10, -6, -6, -10, -10, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -10, -10, -10, -6, 10, 10, -10, -10, -10, -10, -10, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -10, -6, -6, -10, -10, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -10, -10, -10, -6, 10, 10, 10, -6, -6, -6, -6, -6, 10, 10, -6, -10, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -10, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, 10, -6, -6, -6, -6, -10, -6, -6, -6, -6, -6, -6, 10, -6, -6, -6, -6, -6, -10, -6, -6, -6, -6, -6, -6, -6, -6, -6, 10, 10, -6, -10, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, -6, 10, -6, -6, -6, -6, -10, -10, -10, -10, -10, -10, -6, -6, -6, -6, -6, -6, -6, -6, -10, -10, -6, -6, -6, -6, -6, -10, -10, -10, -10, -6, -6, -6, -6]

Observation: Values below the lower bound or above the upper bound were classified as outliers using the 1.5 × IQR rule.

Cell 10 — Outlier records with city information

In [10]:
print("\n" + "=" * 75)
print("OUTLIER RECORDS WITH CITY INFORMATION")
print("=" * 75)

for column in numeric_columns:

    data = df[column].dropna().tolist()

    q1 = manual_quartile(data, 1)
    q3 = manual_quartile(data, 3)

    iqr_value = q3 - q1

    lower_bound = q1 - (1.5 * iqr_value)
    upper_bound = q3 + (1.5 * iqr_value)

    outlier_records = df[
        (df[column] < lower_bound) |
        (df[column] > upper_bound)
    ]

    print("\n" + "-" * 75)
    print("OUTLIERS FOR:", column)
    print("-" * 75)

    if len(outlier_records) > 0:

        display(
            outlier_records[
                ["city", column]
            ]
        )

        print(
            "Number of outlier records:",
            len(outlier_records)
        )

    else:

        print("No outlier records detected.")

    print(
        "\nObservation: The corresponding cities and values "
        "associated with detected outliers were displayed "
        "for further analysis."
    )

===========================================================================
OUTLIER RECORDS WITH CITY INFORMATION
===========================================================================

---------------------------------------------------------------------------
OUTLIERS FOR: temperature_c
---------------------------------------------------------------------------

           city  temperature_c
3201   Dehradun             11
3202   Dehradun             11
3210   Dehradun             11
3960    Gangtok             10
3975    Gangtok             11
...         ...            ...
10905  Srinagar              5
10906  Srinagar              5
10912  Srinagar              9
10913  Srinagar              7
10914  Srinagar              6

[166 rows x 2 columns]

Number of outlier records: 166

Observation: The corresponding cities and values associated with detected outliers were displayed for further analysis.

---------------------------------------------------------------------------
OUTLIERS FOR: relative_humidity
---------------------------------------------------------------------------

                city  relative_humidity
0           Agartala                 98
7           Agartala                 95
8           Agartala                 99
9           Agartala                 90
14          Agartala                 95
...              ...                ...
12048     Vijayawada                 97
12173  Visakhapatnam                 89
12174  Visakhapatnam                 89
12175  Visakhapatnam                 95
12176  Visakhapatnam                 91

[190 rows x 2 columns]

Number of outlier records: 190

Observation: The corresponding cities and values associated with detected outliers were displayed for further analysis.

---------------------------------------------------------------------------
OUTLIERS FOR: wind_speed
---------------------------------------------------------------------------

            city  wind_speed
605        Akola           5
1685    Bareilly           5
1934   Bhavnagar           5
2572     Bikaner           5
2700  Chandigarh           5
3724   Faridabad           5
4204   Ghaziabad           5
4376   Gorakhpur           5
5676    Jabalpur           5
7204        Loni           5
7375     Lucknow           5
7684    Malegaon           5
9004       Noida           5

Number of outlier records: 13

Observation: The corresponding cities and values associated with detected outliers were displayed for further analysis.

---------------------------------------------------------------------------
OUTLIERS FOR: precipitation_amount
---------------------------------------------------------------------------

           city  precipitation_amount
5      Agartala                     1
6      Agartala                    -4
7      Agartala                     4
18     Agartala                    -4
19     Agartala                     4
...         ...                   ...
12295  Warangal                     2
12298  Warangal                    -2
12299  Warangal                     2
12301  Warangal                     1
12304  Warangal                     3

[2277 rows x 2 columns]

Number of outlier records: 2277

Observation: The corresponding cities and values associated with detected outliers were displayed for further analysis.

---------------------------------------------------------------------------
OUTLIERS FOR: cloud_cover
---------------------------------------------------------------------------
No outlier records detected.

Observation: The corresponding cities and values associated with detected outliers were displayed for further analysis.

---------------------------------------------------------------------------
OUTLIERS FOR: lifted_index
---------------------------------------------------------------------------

                city  lifted_index
17          Agartala            -6
18          Agartala            -6
19          Agartala           -10
25          Agartala            -6
49          Agartala            -6
...              ...           ...
12176  Visakhapatnam           -10
12177  Visakhapatnam            -6
12178  Visakhapatnam            -6
12179  Visakhapatnam            -6
12180  Visakhapatnam            -6

[301 rows x 2 columns]

Number of outlier records: 301

Observation: The corresponding cities and values associated with detected outliers were displayed for further analysis.

Cell 11 — Conclusion

In [11]:
print("\n" + "=" * 75)
print("OVERALL CONCLUSION")
print("=" * 75)

print(
    "Frequency, mean, mode, median, variance, standard deviation "
    "and interquartile range were calculated for the weather dataset."
)

print(
    "The same statistical measures were also calculated for "
    "grouped data using city as the grouping variable."
)

print(
    "The statistical calculations were implemented manually "
    "without using built-in statistical functions."
)

print(
    "The 1.5 × IQR method was used to identify outliers in "
    "each numerical weather attribute."
)

print(
    "The analysis provides information about central tendency, "
    "frequency, variability and unusual observations across "
    "different cities."
)

===========================================================================
OVERALL CONCLUSION
===========================================================================
Frequency, mean, mode, median, variance, standard deviation and interquartile range were calculated for the weather dataset.
The same statistical measures were also calculated for grouped data using city as the grouping variable.
The statistical calculations were implemented manually without using built-in statistical functions.
The 1.5 × IQR method was used to identify outliers in each numerical weather attribute.
The analysis provides information about central tendency, frequency, variability and unusual observations across different cities.